# Render.com deployment configuration
services:
  - type: web
    name: ardanmeta-webhook
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ACCESS_TOKEN
        sync: false
      - key: PHONE_NUMBER_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false